
[server]
headless = true
port = "8501"
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#00EEFF"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"
